import { createElement } from "lwc";
import ViewAsModalGenerateComercialPlan from "c/viewAsModalGenerateComercialPlan";

describe("c-view-as-modal-generate-comercial-plan", () => {
  afterEach(() => {
    // The jsdom instance is shared across test cases in a single file so reset the DOM
    while (document.body.firstChild) {
      document.body.removeChild(document.body.firstChild);
    }
  });

  it("TODO: test case generated by CLI command, please fill in test logic", () => {
    // Arrange
    const element = createElement("c-view-as-modal-generate-comercial-plan", {
      is: ViewAsModalGenerateComercialPlan
    });

    // Act
    document.body.appendChild(element);

    // Assert
    expect(1).toBe(1);
  });
});
