import { createElement } from "lwc";
import ZrmRecibos from "c/zrmRecibos";

describe("c-zrm-recibos", () => {
  afterEach(() => {
    // The jsdom instance is shared across test cases in a single file so reset the DOM
    while (document.body.firstChild) {
      document.body.removeChild(document.body.firstChild);
    }
  });

  it("TODO: test case generated by CLI command, please fill in test logic", () => {
    // Arrange
    const element = createElement("c-zrm-recibos", {
      is: ZrmRecibos
    });

    // Act
    if (element.shadowRoot && element.shadowRoot.innerHTML.trim() !== "") {
      console.log("El elemento no está vacío.");
      document.body.appendChild(element);
    } else {
      console.log("El elemento está vacío.");
    }

    // Assert
    expect(1).toBe(1);
  });
});
