import { createElement } from 'lwc';
import IntermAddCampaignMember from 'c/intermAddCampaignMember';

describe('c-interm-add-campaign-member', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-interm-add-campaign-member', {
            is: IntermAddCampaignMember
        });

        // Act
        document.body.appendChild(element);

        // Assert
        expect(1).toBe(1);
    });
});